from __future__ import annotations

import json
import re
from typing import Any

import ollama
from fastapi import APIRouter
from pydantic import BaseModel

from .. import model_registry
from ..agent import tools
from ..config import settings
from .preview import PreviewStartRequest, start_preview

router = APIRouter(prefix="/api/tasks", tags=["tasks"])

ALLOWED_GENERATED_SUFFIXES = {".html", ".css", ".js", ".py", ".c", ".h", ".md", ".txt", ".json"}
MAX_GENERATED_FILES = 8
MAX_GENERATED_CHARS = 200_000


class TaskPlanRequest(BaseModel):
    prompt: str


class TaskPlanResponse(BaseModel):
    goal: str
    mode: str
    steps: list[str]
    suggested_files: list[dict[str, str]]
    verify_commands: list[str]
    notes: list[str]


class TaskRunRequest(BaseModel):
    prompt: str
    preview: bool = True
    overwrite: bool = True


class TaskRunStep(BaseModel):
    name: str
    status: str
    detail: str


class TaskRunResponse(BaseModel):
    goal: str
    mode: str
    ok: bool
    created_files: list[str]
    preview_url: str | None
    steps: list[TaskRunStep]
    notes: list[str]


@router.post("/plan", response_model=TaskPlanResponse)
async def plan_task(body: TaskPlanRequest) -> TaskPlanResponse:
    return build_plan(body.prompt)


@router.post("/run", response_model=TaskRunResponse)
async def run_task(body: TaskRunRequest) -> TaskRunResponse:
    """Run the autonomous build loop: plan -> write -> verify -> preview.

    Known safe templates run deterministically. Unknown build prompts fall back to
    a strict JSON file generator powered by the selected local Ollama model.
    """
    plan = build_plan(body.prompt)
    steps: list[TaskRunStep] = [TaskRunStep(name="plan", status="ok", detail=f"Selected {plan.mode} workflow.")]
    notes = list(plan.notes)

    if not plan.suggested_files and _looks_like_build_request(body.prompt):
        generated = await _generate_json_file_plan(body.prompt, steps)
        if generated:
            plan = TaskPlanResponse(
                goal=body.prompt.strip(),
                mode="json-generated-task",
                steps=["Generate a JSON file plan.", "Write generated files.", "Run lightweight verification.", "Open preview for HTML output."],
                suggested_files=generated,
                verify_commands=[],
                notes=["Files were generated by the local model in strict JSON format and validated before writing."],
            )
            notes = list(plan.notes)

    created_files = _write_suggested_files(plan, body.overwrite, steps)
    if not plan.suggested_files:
        steps.append(
            TaskRunStep(
                name="write",
                status="skipped",
                detail="No deterministic template or valid JSON file plan was available for this prompt.",
            )
        )
        return TaskRunResponse(
            goal=plan.goal,
            mode=plan.mode,
            ok=False,
            created_files=created_files,
            preview_url=None,
            steps=steps,
            notes=notes + ["Try a more concrete build prompt, or use chat mode to ask for code/instructions."],
        )

    verify_ok = _verify_created_files(plan, created_files, steps)
    preview_url = await _maybe_start_preview(body.preview, created_files, verify_ok, steps)

    return TaskRunResponse(
        goal=plan.goal,
        mode=plan.mode,
        ok=verify_ok,
        created_files=created_files,
        preview_url=preview_url,
        steps=steps,
        notes=notes,
    )


def build_plan(prompt: str) -> TaskPlanResponse:
    prompt = prompt.strip()
    lower = prompt.lower()
    if "bouncing" in lower and "ball" in lower:
        return _bouncing_ball_plan(prompt)
    if any(word in lower for word in ["bug", "fix", "error", "traceback", "failing"]):
        return _bugfix_plan(prompt)
    if any(word in lower for word in ["large file", "100000", "100,000", "huge file"]):
        return _large_file_plan(prompt)
    if _looks_like_build_request(prompt):
        return _generated_task_plan(prompt)
    return _general_plan(prompt)


def _looks_like_build_request(prompt: str) -> bool:
    text = prompt.lower()
    return bool(re.search(r"\b(make|build|create|generate|write|develop|implement)\b", text)) and bool(
        re.search(r"\b(game|app|application|website|web page|html|system|tool|program|project|calculator|todo|quiz|os|operating system)\b", text)
    )


async def _generate_json_file_plan(prompt: str, steps: list[TaskRunStep]) -> list[dict[str, str]]:
    system = (
        "You generate small coding project files. Return ONLY valid JSON with this exact shape: "
        "{\"files\":[{\"path\":\"relative/path.ext\",\"content\":\"full file content\"}],\"notes\":[\"...\"]}. "
        "Use relative paths only. Do not use markdown fences. Prefer one runnable HTML file for browser games, "
        "or a small Python/C project when requested. Keep the project compact."
    )
    user = f"Create the files for this request: {prompt}"
    try:
        response = await ollama.AsyncClient(host=settings.ollama_host).chat(
            model=model_registry.get_current_model(),
            messages=[{"role": "system", "content": system}, {"role": "user", "content": user}],
            stream=False,
            think=False,
            options={"temperature": 0.1, "num_ctx": settings.model_num_ctx, "num_predict": settings.max_model_output_tokens},
        )
    except Exception as exc:
        steps.append(TaskRunStep(name="generate", status="error", detail=f"Local model generation failed: {exc}"))
        return []

    content = (response.get("message") or {}).get("content") or ""
    payload = _extract_json_payload(content)
    if not payload:
        steps.append(TaskRunStep(name="generate", status="error", detail="Model did not return valid JSON."))
        return []
    files = _validated_generated_files(payload, steps)
    if files:
        steps.append(TaskRunStep(name="generate", status="ok", detail=f"Generated {len(files)} file(s) from JSON plan."))
    return files


def _extract_json_payload(text: str) -> dict[str, Any] | None:
    text = text.strip()
    candidates = [text]
    match = re.search(r"\{.*\}", text, flags=re.DOTALL)
    if match:
        candidates.append(match.group(0))
    for candidate in candidates:
        try:
            payload = json.loads(candidate)
        except json.JSONDecodeError:
            continue
        if isinstance(payload, dict):
            return payload
    return None


def _validated_generated_files(payload: dict[str, Any], steps: list[TaskRunStep]) -> list[dict[str, str]]:
    raw_files = payload.get("files")
    if not isinstance(raw_files, list):
        steps.append(TaskRunStep(name="validate", status="error", detail="JSON payload does not contain a files list."))
        return []
    files: list[dict[str, str]] = []
    total_chars = 0
    for raw in raw_files[:MAX_GENERATED_FILES]:
        if not isinstance(raw, dict):
            continue
        path = str(raw.get("path") or "").strip().replace("\\", "/")
        content = raw.get("content")
        if not path or not isinstance(content, str):
            continue
        suffix = "." + path.rsplit(".", 1)[-1].lower() if "." in path else ""
        if suffix not in ALLOWED_GENERATED_SUFFIXES:
            steps.append(TaskRunStep(name="validate", status="skipped", detail=f"Skipped unsupported generated file type: {path}"))
            continue
        try:
            tools.resolve_in_workspace(path)
        except ValueError as exc:
            steps.append(TaskRunStep(name="validate", status="skipped", detail=str(exc)))
            continue
        total_chars += len(content)
        if total_chars > MAX_GENERATED_CHARS:
            steps.append(TaskRunStep(name="validate", status="error", detail="Generated project exceeded size limit."))
            break
        files.append({"path": path, "content": content})
    return files


def _write_suggested_files(plan: TaskPlanResponse, overwrite: bool, steps: list[TaskRunStep]) -> list[str]:
    created_files: list[str] = []
    for item in plan.suggested_files:
        path = item["path"]
        content = item["content"]
        existing = tools.read_file(path)
        if not overwrite and not existing.startswith("Error:"):
            steps.append(TaskRunStep(name="write", status="skipped", detail=f"{path} already exists."))
            continue
        result = tools.write_file(path, content)
        created_files.append(path)
        status = "error" if result.startswith("Error") else "ok"
        steps.append(TaskRunStep(name="write", status=status, detail=result))
    return created_files


def _verify_created_files(plan: TaskPlanResponse, created_files: list[str], steps: list[TaskRunStep]) -> bool:
    if not created_files:
        steps.append(TaskRunStep(name="verify", status="error", detail="No files were created."))
        return False
    ok = True
    for path in created_files:
        content = tools.read_file(path)
        if content.startswith("Error:") or not content.strip():
            steps.append(TaskRunStep(name="verify", status="error", detail=f"{path} is missing or empty."))
            ok = False
            continue
        if path.endswith(".py"):
            try:
                compile(content, path, "exec")
                steps.append(TaskRunStep(name="verify", status="ok", detail=f"{path} Python syntax verified."))
            except SyntaxError as exc:
                steps.append(TaskRunStep(name="verify", status="error", detail=f"{path} syntax error: {exc}"))
                ok = False
        elif path.endswith(".html"):
            html_ok = "<html" in content.lower() or "<canvas" in content.lower() or "<script" in content.lower()
            steps.append(TaskRunStep(name="verify", status="ok" if html_ok else "warning", detail=f"{path} HTML structure checked."))
            ok = ok and html_ok
        elif path.endswith(".c"):
            c_ok = "main(" in content or "main (" in content
            steps.append(TaskRunStep(name="verify", status="ok" if c_ok else "warning", detail=f"{path} C entry point checked."))
        else:
            steps.append(TaskRunStep(name="verify", status="ok", detail=f"{path} written and readable."))
    return ok


async def _maybe_start_preview(preview: bool, created_files: list[str], verify_ok: bool, steps: list[TaskRunStep]) -> str | None:
    if not preview or not verify_ok:
        return None
    html_file = next((path for path in created_files if path.endswith(".html")), None)
    if not html_file:
        return None
    preview_state = await start_preview(PreviewStartRequest(path=html_file, port=9000))
    steps.append(TaskRunStep(name="preview", status="ok", detail=f"Preview ready at {preview_state.url}"))
    return preview_state.url


def _bouncing_ball_plan(prompt: str) -> TaskPlanResponse:
    html = """<!doctype html>
<html>
<head>
  <meta charset=\"utf-8\" />
  <title>Bouncing Ball</title>
  <style>body{margin:0;background:#101820;color:white;font-family:sans-serif}canvas{display:block;margin:24px auto;background:#f7f7f7;border:2px solid #333}</style>
</head>
<body>
  <canvas id=\"game\" width=\"640\" height=\"360\"></canvas>
  <script>
    const canvas = document.getElementById('game');
    const ctx = canvas.getContext('2d');
    const ball = { x: 80, y: 80, vx: 4, vy: 3, r: 18 };
    function tick() {
      ctx.clearRect(0, 0, canvas.width, canvas.height);
      ball.x += ball.vx; ball.y += ball.vy;
      if (ball.x < ball.r || ball.x > canvas.width - ball.r) ball.vx *= -1;
      if (ball.y < ball.r || ball.y > canvas.height - ball.r) ball.vy *= -1;
      ctx.beginPath(); ctx.arc(ball.x, ball.y, ball.r, 0, Math.PI * 2);
      ctx.fillStyle = '#7c3aed'; ctx.fill();
      requestAnimationFrame(tick);
    }
    tick();
  </script>
</body>
</html>
"""
    return TaskPlanResponse(
        goal=prompt,
        mode="game-generator",
        steps=["Create an HTML canvas game file in the workspace.", "Verify the game structure.", "Start preview server."],
        suggested_files=[{"path": "bouncing_ball.html", "content": html}],
        verify_commands=["Open http://127.0.0.1:9000/bouncing_ball.html"],
        notes=["This deterministic template is used for bouncing ball prompts."],
    )


def _generated_task_plan(prompt: str) -> TaskPlanResponse:
    return TaskPlanResponse(
        goal=prompt,
        mode="json-generator-fallback",
        steps=["Classify the request.", "Ask the local model for a strict JSON file plan.", "Validate paths and file types.", "Write files and run lightweight verification."],
        suggested_files=[],
        verify_commands=[],
        notes=["No fixed template matched; autonomous run will try the JSON file generator fallback."],
    )


def _bugfix_plan(prompt: str) -> TaskPlanResponse:
    return TaskPlanResponse(
        goal=prompt,
        mode="bugfix",
        steps=["Run project_index to map files and symbols.", "Use search_files for the error name or stack trace.", "Use read_file_range around failing lines.", "Patch with replace_in_file.", "Run verification."],
        suggested_files=[],
        verify_commands=["python -m pytest -q", "npm test", "python <script>.py"],
        notes=["Bugfix tasks require existing project context and still use the normal approval-gated tools."],
    )


def _large_file_plan(prompt: str) -> TaskPlanResponse:
    return TaskPlanResponse(
        goal=prompt,
        mode="large-file-handler",
        steps=["Use project_index to find files.", "Use search_files to locate targets.", "Use read_file_range in bounded windows.", "Patch only exact ranges.", "Run focused verification."],
        suggested_files=[],
        verify_commands=["python -m pytest -q", "python -m py_compile <file>.py"],
        notes=["Do not paste or load a 100000-line file into the model at once."],
    )


def _general_plan(prompt: str) -> TaskPlanResponse:
    return TaskPlanResponse(
        goal=prompt,
        mode="coding-task",
        steps=["Use project_index to understand the workspace.", "Identify relevant files/ranges.", "Make changes with write_file or replace_in_file.", "Run verification."],
        suggested_files=[],
        verify_commands=["python -m pytest -q"],
        notes=["This is a planning scaffold for chat/tool mode."],
    )
